### PR TITLE
Fixed the NullReferenceException on the StopLogging() call, #1.

### PR DESCRIPTION
**Pull request by yallie**
Sorry for the whitespace changes.

### CODE REVIEW

**Comment by dbelikov** [comment]
Sorry, I'm not fully familiar with GitHub UI (both companies I worked at use perforce-based systems) and I don't have any time to dedicate to this project.

Since you have the desire to continue developing this project, I find you fully worthy to take entirely over the future fate of this project.

Would it be possible to grant you full permissions to push any changes to this project at any time without any reviews? And if yes, how do I do it via the GitHub interface?

**Comment by yallie** [comment]
Hello Dmitry,

thanks for your trust.
I guess it's done using repository settings -> Collaborators tab:

image

**Comment by dbelikov** [comment]
Excellent. I've enlisted you into the collaborators. I believe it's gated by you accepting the invite.

However by the looks of it, it only grants you the push access to the repository. Where do I grant you permissions to add more collaborators as you see fit?

**Comment by yallie** [comment]
>Excellent. I've enlisted you into the collaborators. I believe it's gated by you accepting the invite.

Thank you! It worked, I was able to merge this PR.

>Where do I grant you permissions to add more collaborators as you see fit?

According to the Github docs it seems to be only possible for the organizations.
User repositories have only two access levels: repository owner and collaborators.
https://help.github.com/articles/permission-levels-for-a-user-account-repository/

Can you create an organization GenuineChannels and transfer the repository ownership?
As an owner you'll be able to add more organization members with admin rights.

image

As you transfer the ownership to the organization, your old repository URL
will be redirected to the new location automatically. Transfer button is located
on your repository Settings tab, at the bottom of the page:

image

Thanks!

**Pull request merged**
